# Rename this file to config.yml and fill all necessary lines

# Telegram client configuration
telegram:
  api_id: <Your API ID from https://my.telegram.org>
  api_hash: <Your API hash from https://my.telegram.org>
  session_file: </path/to/your/client.session>
  phone_number: <Your phone number>

  # Chat types which should be monitored
  chat_types:
    - contact # Users added as contact
    - user # Users not added as contact
    - group # Groups (including mega groups)
    - channel # Channels (excluding mega groups)

  # List of chats to monitor additionally to those specified using "chat_types"
  # The command "list-chats" can be used to get specific IDs
  additional_chats:
    - <id 1>
    - <id 2>
    - ...

# Telegram bot configuration
telegram-bot:
  bot_token: <Bot authorization token, can be obtained from the @BotFather bot>
  bot_session_file: </path/to/your/bot.session>

  # List of users who are banned
  banned_users:
    - <username 1>
    - <username 2>
    - ...

# Elasticsearch client configuration
elasticsearch:
  host: http://localhost:9200
  index:
    # Specify the date format to use as the index suffix
    # "-" is automatically added between the prefix and the date
    # The following configuration will result in an index like "telegram-2020.03.18"
    # Without "date_format" the index will be named "telegram"
    date_format: "%Y.%m.%d"
    prefix: telegram